services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brotkrueml\FormRateLimit\:
    resource: '../Classes/*'
    exclude: '../Classes/Extension.php'

  Brotkrueml\FormRateLimit\RateLimiter\FormRateLimitFactory:
    arguments:
      $storage: '@TYPO3\CMS\Core\RateLimiter\Storage\CachingFrameworkStorage'
